// Chatgpt generated ideas
const newNoteAdjectives: string[] = [
  "Fantastic",
  "Innovative",
  "Trailblazing",
  "Pioneering",
  "Revolutionary",
  "Groundbreaking",
  "Unprecedented",
  "Cutting-edge",
  "Avant-garde",
  "Bantabulous",
  "Game-changing",
  "Splendific",
  "Wondermazing",
  "Fantasmagorical",
  "Majestifabulous",
  "Magnifitastic",
  "Earth-shattering",
  "Mind-bending",
  "Paradigm-shifting",
  "Life-altering",
  "Jaw-dropping",
  "Eye-opening",
  "Transformative",
  "Universe-bending",
];
